# Generated by Django 5.2.7 on 2025-11-02 13:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sweet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sweet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='category',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='sweet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
